### ISSUE TITLE
Total size

### ISSUE THREAD

**Issue by gingerbeardman** [rsn8887/Enigma#3] opened 2019-02-26 18:00 UTC
92MB seems a bit much for this game? I guess it's mostly the music?

It took ages to download on my Switch and even longer to decompress/install.

**Comment by rsn8887** [comment] 2019-02-26 21:53
This game is huge. It has many thousands of levels and each one has a png thumbnail. 

There's code to support zipped level files, which will make installation much faster.

I just never got around to testing it, mostly because the original Windows/OSX version is supplied with unzipped files, too. So I suspected there's a reason for that and probably some bug or problem with the builtin zip support.

Here's the comment in the code about zip file support, if you want to test it:
// file may be zipped - for "levels/Sokoban/mic_60.xml" we will look for
// "mic_60.xml" and "Sokoban/mic_60.xml" at "levels/Sokoban.zip"

**Comment by gingerbeardman** [comment] 2019-02-26 23:04
In the case of many images you may want to look at optimising your images using ImageOptim, or similar?

**Comment by rsn8887** [comment] 2019-02-27 08:00
Why? 92 MB is not large in modern times. This is still smaller than even the smallest Indie games on the Nintendo shop.

The problem is not size. The problem is the 10,000 tiny files. For some reason it takes the Switch forever to unzip so many small files.

**Comment by gingerbeardman** [comment] 2019-02-27 10:10
Why? Why not? It takes minimal effort - drag and drop and wait a while.

As I explained, on the broadband I am using right now it took an age to download and even longer to unzip. Even if the download could be sped up that would help, and if less data is being written by the Switch maybe that will be sped up too? For Switch eShop games I have to leave the download overnight.

I'll optimise the images now, and make a PR

**Comment by rsn8887** [comment] 2019-02-27 16:19
I will look into this whenever I find time. If ImageOptim truly reduces the size without changing the quality, I might do it for a future release.

**Comment by gingerbeardman** [comment] 2019-02-27 16:20
Sure thing, no expectations 

PR is here https://github.com/rsn8887/Enigma/pull/4

I am also running a more extensive image optimisation just to see what a difference that makes. If it's worthwhile I'll push it to the current PR.

**Comment by rsn8887** [comment] 2019-02-27 16:33
I merged your PR but realized the attic/ files are not used and shouldn't be optimized to stay compatible with upstream.

The only files used are the ones in data.zip, so I only kept that commit. Thanks!

**Closed as completed** 2019-02-27 16:33 UTC
