### ISSUE TITLE
Game crashes with "C2-12828-1" error on startup 

### ISSUE THREAD

**Issue by J-Iszatt** [rsn8887/Enigma#1] opened 2018-03-22 16:15 UTC
I can not get the game to run on a vita 1000/ 3g system with enso 3.60.
Tested version were 1.04 and 1.05 with the according data.zip file-packages.

As "Saved Core File Succeded. ux0:data/psp2core - 1521716995 - 0x0000052b0d-eboot.bin.psp2dmp" indicates, i might be able to send a log-file(?).

With an other system at hand (wifi), i will try if the program runs on that system as soon as i can get my hands on it.

The data strucutre of the files is "ux0:data/enigma" with the following subfolders: "data", "doc", "locale" and "thumbs-120x78"
and single files:
"OXYD1IBM.DAT", "OXYDEX.DAT", "OXYDMGG.DAT", "OXYDMIBM.DAT" and "PEROXYD.DAT"

*Edit: I almost forgot the most important part:
Great port!!! Keep up the good work and dont be to disapointed as there is not much feedback coming in from the wololo forums

**Comment by rsn8887** [comment] 2018-03-23 14:19
I suspect that something went wrong with extracting or transferring the files in data.zip. Data.zip contains 9891 small files with some long and strange filenames. Maybe your FTP client or copy method you used skipped some files...

I used Filezilla FTP client to transfer the files to the Vita.

I just did a fresh install to see if I can reproduce your bug, but it works for me.

I suggest you try the following:
- download latest enigma_1.06.vpk and data.zip from github release page
- uninstall Enigma
- delete ux0:/data/enigma
- extract data.zip into some folder on your computer
- use Filezilla FTP Client to transfer the folder "enigma" to your Vita to ux0:/data/. 
- you should see exactly 9891 files transferred with zero skipped files in the end. It takes a while to transfer all the files via FTP.
- use Vitashell to install the latest enigma_1.06.vpk and launch it. Enigma takes quite a while to load, about 30 seconds or so until you first hear the menu music and then see the menu appear.

Please post again so I know if this fixed your problem or not.

I originally used MacOS to extract and transfer data.zip files, but I just tried it with my Windows 10 desktop, and it also worked.

**Comment by rsn8887** [comment] 2018-03-23 16:29
Fixed by using FTP transfer instead of direct Vitashell USB mount.

**Closed as completed by rsn8887** 2018-03-23 16:29 UTC
